Benchmark spdk test

diff --git a/.github/workflows/pr-code-coverage.yaml b/.github/workflows/pr-code-coverage.yaml
--- a/.github/workflows/pr-code-coverage.yaml
+++ b/.github/workflows/pr-code-coverage.yaml
@@ -49,13 +49,18 @@ jobs:
           tests/unit/build/coverage.info
           tests/unit/build/coverage.txt
 
-    - name: "Read coverage.txt into env var"
+    - name: Read coverage.txt into env var
       if: always()
       id: covsummary
       run: |
-        echo 'summary<<EOF' >> $GITHUB_OUTPUT
-        tail -n 20 tests/unit/build/coverage.txt || echo "coverage.txt not found" >> $GITHUB_OUTPUT
-        echo 'EOF' >> $GITHUB_OUTPUT
+        {
+          echo "summary<<EOF"
+          tail -n 20 tests/unit/build/coverage.txt || echo "coverage.txt not found"
+          echo "EOF"
+        } >> $GITHUB_OUTPUT
+
+    - name: Debug Output
+      run: echo "${{ steps.covsummary.outputs.summary }}"
 
     - name: "PR Comment: Coverage Summary"
       if: always()
